### ISSUE TITLE
Last Ping ERROR

### ISSUE THREAD

**Issue by reinforce** [furlongm/openvpn-monitor#144]
Last ping not work as should, always ERROR

OpenVPN version: 2.4.7
OpenVPN-Monitor version: on master branch

The issue is over there: 
https://github.com/furlongm/openvpn-monitor/blob/master/openvpn-monitor.py#L449

What actyally goes wrong: 
Routing table(command 'status 3') returns MAC addresses instead of local IP and sessions lookup work wrong.

**Comment by furlongm** [comment]
Can you post debug output as described in the README?

**Comment by reinforce** [comment]
Debug output: https://gist.github.com/reinforce/5d05ce39640587df54368f1af004def4

**Comment by furlongm** [comment]
Can you try this branch?

https://github.com/furlongm/openvpn-monitor/blob/support-mac-addresses/openvpn-monitor.py

**Comment by reinforce** [comment]
Tested with support-mac-addresses branch. Last ping works. Thank you!

**Comment by furlongm** [comment]
The underlying issue is that you are using `dev tap` instead of `dev tun`. If you change that it will work correctly all the time. Note that the above fix will not work with ipv6 addresses, so I have changed the `last seen` message from `ERROR` to `Unknown`. Again, using a tun device instead of a tap device will also fix the issue with ipv6.
