### ISSUE TITLE
GeoIP is Unknown 

### ISSUE THREAD

**Issue by eth-man** [furlongm/openvpn-monitor#148]
Hi, 
i can see the locations if running the python script but not via web page
 
![image](https://user-images.githubusercontent.com/8633885/79128495-e8f91280-7da3-11ea-8608-20d440b43ec3.png)

![image](https://user-images.githubusercontent.com/8633885/79128700-442b0500-7da4-11ea-82b0-768d885a5def.png)

**Comment by freetextmike** [comment]
i have the same problem, i already updated the location for the GeoIPCity.dat and still not working 

any solutions to this issue?

**Comment by u0m3** [comment]
@eth-man This might sound like an idiotic thing to ask, but are you sure the displayed webpage is generated by the script you ran from command line? And if so, is it possible that you ran it from console as a different user than the *service* runs it as?
Because I can only think of 2 things that would have the result you are describing: either you have two copies of *openvpn-monitor* and the copy you ran from console is different from the one that generated the webpage, or there are some permission issues that make it so the *service* generating the webpage can not read the GeoIP database file.
Or maybe somewhere in-between?!

@freetextmike `GeoIPCity.dat` looks like the old format for the GeoIP database files. As far as I know **openvpn-monitor** uses the **geoip2** python module that is only able to read the new format.
You could try to download GeoIPLite database files by hand and place them somewhere they would be accessible to the service and set `geoip_data=/my/path/to/GeoIPLiteDatabase/GeoLite2-City.mmdb` in `openvpn-monitor.conf`.

**Comment by freetextmike** [comment]
> @eth-man This might sound like an idiotic thing to ask, but are you sure the displayed webpage is generated by the script you ran from command line? And if so, is it possible that you ran it from console as a different user than the _service_ runs it as?
> Because I can only think of 2 things that would have the result you are describing: either you have two copies of _openvpn-monitor_ and the copy you ran from console is different from the one that generated the webpage, or there are some permission issues that make it so the _service_ generating the webpage can not read the GeoIP database file.
> Or maybe somewhere in-between?!
> 
> @freetextmike `GeoIPCity.dat` looks like the old format for the GeoIP database files. As far as I know **openvpn-monitor** uses the **geoip2** python module that is only able to read the new format.
> You could try to download GeoIPLite database files by hand and place them somewhere they would be accessible to the service and set `geoip_data=/my/path/to/GeoIPLiteDatabase/GeoLite2-City.mmdb` in `openvpn-monitor.conf`.

i managed to fix this 

https://github.com/freetextmike/monitoring

**Comment by eth-man** [comment]
solved by installing the missing package python-geoip2 , thank you
