### ISSUE TITLE
Not displaying flags and logos

### ISSUE THREAD

**Issue by tuchinsky** [furlongm/openvpn-monitor#36]
I'm using apache and centos 7

/etc/httpd/conf.d/openvpn-monitor.conf:
`WSGIScriptAlias / /var/www/html/openvpn-monitor/openvpn-monitor.py`

I put logo.png in /var/www/html/openvpn-monitor folder and set logo option in openvpn-monitor.conf:
```
[OpenVPN-Monitor]
...
logo=logo.png
...
```

But logo not showing in interface. If try open url http://myserver/logo.png, then i get 404 error. Flags also not displayed

```
"GET /flags/ru.png HTTP/1.1" 404 736 "http://myserver/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

"GET /logo.png HTTP/1.1" 404 732 "http://myserver/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
```

**Comment by furlongm** [comment]
Can you put the logo in the images subdir and see if that works?

**Comment by tuchinsky** [comment]
yes, it's work. Thanks!

**Comment by tuchinsky** [comment]
yes, it's work. Thanks!

**Comment by Jayky** [comment]
Hi,

I*m using armbian and apache2. The openvpn-monitor works but no logos nor flags are displayed. I've read all about those issues and non of the mentioned fixes worked for me. 

I used for installation /var/www/html/openvpn-monitor, my logo is in the subdir images. What settings/configs or else should I send you, so that you could analyse what is not working?
