### ISSUE TITLE
Password protected management interface

### ISSUE THREAD

**Issue by nathank1989** [furlongm/openvpn-monitor#45]
It looks like I can add multiple VPNs so I want to monitor some remote ones but obviously don't want to expose the management console to the internet completely. Is there a way to incorporate a password answer for a file defined in the openvpn server.conf?

**Comment by furlongm** [comment]
I'm not sure I understand what you are trying to achieve. Do you have an example of what you mean?

**Comment by scomoletti** [comment]
The management interface in OpenVPN can be password protected..which I think is a good idea to support. 
That said, I wouldn't leave the management interface open to the internet even if it had a password. It may be better to run an openvpn client on your openvpn-monitor server so that it has a local connection to the openvpn server your managing.. and you can run multiple clients on a single host if you need to have openvpn-monitor talk to multiple remote servers.

**Comment by furlongm** [comment]
@scomoletti this sounds like a good idea. I haven't used this functionality before. Do you have a quick rundown of how it works?

**Comment by scomoletti** [comment]
I'll admit I havent tested it yet myself. Just read about it in the docs. 

--management IP port [pw-file]
Enable a TCP server on IP:port to handle daemon management functions. pw-file, if specified, is a password file (password on first line) or "stdin" to prompt from standard input. The password provided will set the password which TCP clients will need to provide in order to access management functions.

**Comment by scomoletti** [comment]
I have password support working in a local copy.. will submit a pull request tomorrow after a little more testing.

**Comment by ValkiryXDA** [comment]
Hows this coming along? Id love to add this feature and not have to htpsswd apache

**Comment by tony-caffe** [comment]
Why would you not send this web interface over https using htpasswd? Seems like an easy way to mitigate in the mean time and still very secure.

```
<Directory "/example/path/">
...
   AuthName "Site OpenVPN Management Access"
   AuthType Basic
   AuthUserFile /etc/example/location/htpasswd.users
   Require valid-user
...
</Directory>
```

**Comment by scomoletti** [comment]
Distracted by work and some travel. I'll push to my repo so you can
review.. it still needs some work.. proper error message on when it fails
due to invalid password for example. I've been using it in my dev
environment with 8 server instances but only have 2 clients at the moment
so not much to see.

**Comment by scomoletti** [comment]
@tony-caffe and @ValkiryXDA , The password support we are discussing is for the OpenVPN management interface which OpenVPN-Monitor uses to collect data and not the web page that it displays that data on. What you propose with htpasswd is a good practice however.

**Comment by tony-caffe** [comment]
@scomoletti This seems very useful but I guess I dont fully understand how its implemented? For me I use my management interface on localhost in server.conf, so this would allow a more secure backend communication if the OpenVPN server and the Monitor are on a different network location?

```
# provide interface for lots of management goodness
management localhost 7505
```

**Comment by scomoletti** [comment]
@tony-caffe Yes, this is more an issue when OpenVPN-Monitor is not local segment to the server it is connecting to via the mgmt interface. Ideally one should use an encrypted connection if it leaves the local lan which is why I mentioned an oob vpn tunnel for management purposes.

Now, why OpenVPN did this.. I think this is one of the differences between the community and enterprise editions of the product. They need to retain something to entice customers to pay for the enterprise edition.

**Comment by TheAmigo** [comment]
@scomoletti I went a different route.  The OpenVPN management interface doesn't use encryption.  So even if you password that and have a way for openvpn-monitor to read that password from a file, the management connection (including password) is all in plain text (granted, it's probably over your internal network, but still).

I created a systemd service file that creates an SSH tunnel to the remote OpenVPN server, then openvpn-monitor only needs to connect to localhost:5557 and all the traffic is encrypted (also doesn't require a password for OpenVPN management because it's connecting to the loopback interface).  With the right arguments, SSH can monitor the connection.  If the connection is lost, it will exit and systemd will restart it.  Adjust ServerAliveInterval to your liking.  The default for ServerAliveCountMax is 3 so my sample below won't try to restart a dead ssh connection until 30 seconds.

Bonus points if you take my example and make it into an @.service file so you can launch multiple instances (in case you have several OpenVPN servers).

Create this file as: /etc/systemd/system/openvpn_management_tunnel.service
```
[Unit]
Description=create ssh tunnel to vpn2 for vpn monitoring
After=network.target
[Service]
ExecStart=/bin/ssh -o ServerAliveInterval=10 -N -o ExitOnForwardFailure=yes -L 5557:localhost:5555 vpn2.example.local
Type=simple
Restart=always
```
